### ISSUE TITLE
MailChimp welcome email not sending

### ISSUE THREAD

**Issue by jem-computer** [RailsApps/rails-prelaunch-signup#5] opened 2012-06-04 18:33 UTC
Hey - I can't get my MailChimp welcome email to send. The add_user_to_mailchimp code works and adds new users to my MailChimp list, it just doesn't send a welcome email. Maybe not technically an error on your end but is there anything you can think I might have missed?

Again, I have the list 'Visitors' set up and users are being added to it; is there anything on the MailChimp side I need to do to activate the welcome email?

``` ruby
  def add_user_to_mailchimp
    unless self.email.include?('@example.com')
      mailchimp = Hominid::API.new(ENV["MAILCHIMP_API_KEY"])
      list_id = mailchimp.find_list_id_by_name "Visitors"
      info = { }
      result = mailchimp.list_subscribe(list_id, self.email, info, 'html', false, true, false, true)
      Rails.logger.info("MAILCHIMP SUBSCRIBE: result #{result.inspect} for #{self.email}")
    end
  end
```

**Comment by DanielKehoe** [comment] 2012-06-04 18:38
Sounds like a MailChimp configuration issue. I'm not the one who can help with this. Has MailChimp support been able to help? I'll leave this issue open and encourage you to post the solution when you find it in case others run into the issue.

-- Daniel

**Comment by jem-computer** [comment] 2012-06-10 08:23
…it was going to my spam folder. I feel so, so stupid right now.

(but something to bear in mind - apparently Gmail thinks MailChimp's default welcome messages are too spammy; change yours!)

**Comment by Chandra736** [comment] 2012-06-13 17:41
Hi For me above method is not working I am getting the following error any idea what could be wrong I am running on windows and hardcoded the api in the method: If I comment out that method rest works fine.
---------method-------------

def add_user_to_mailchimp
    unless self.email.include?('@example.com')
      mailchimp = Hominid::API.new('entirekeypastedhere')
      list_id = mailchimp.find_list_id_by_name "visitors"
      info = { }
     # result = mailchimp.list_subscribe(list_id, self.email, info, 'html', false, true, false, true)
     #Rails.logger.info("MAILCHIMP SUBSCRIBE: result #{result.inspect} for #{self.email}")
    end
  end
------------------Errors---------------
Completed 500 Internal Server Error in 188ms

SocketError (getaddrinfo: No such host is known. ):
  app/models/user.rb:57:in `add_user_to_mailchimp'
  app/controllers/registrations_controller.rb:7:in`create'

**Comment by DanielKehoe** [comment] 2012-06-13 17:48
Make sure you are using the correct API key. Mandrill and Mailchimp have different keys. The error looks like what happens when the API key is wrong.

**Comment by Chandra736** [comment] 2012-06-14 17:22
I am using Mandrill API Key to me key looks correct as when I comment this method code from admin page after login with user@example.com I am able to send confirmation email. And I verified the mandrill monitors my sent emails and show the information correctly.

**Comment by DanielKehoe** [comment] 2012-06-14 18:05
Is your Mailchimp API key different from your Mandrill API Key? Or are they the same?

**Comment by Chandra736** [comment] 2012-06-14 18:29
Yes, but looks like something wrong with the configuration of Mailchimp in mailchimp account. The following error comes when I disable in mail chimp "<104> Invalid Mailchimp API Key:" but enabled above error comes which I kept in initial comments.

Looks like there is something wrong with this line "mailchimp.find_list_id_by_name "visitors"" how it find the name visitors by default it label is "Mandril;" do I need create any visitors id inside mailchimp account.

**Comment by DanielKehoe** [comment] 2012-06-14 18:32
Have you created a mailChimp list named "visitors"?

**Comment by Chandra736** [comment] 2012-06-15 09:03
No, but now I have created one and test still same result.

**Comment by Chandra736** [comment] 2012-06-16 07:04
Daniel, it is very silly I have changed the line as "mailchimp.find_list_id_by_name("visitors")" from mailchimp.find_list_id_by_name "visitors" it started working :)

**Comment by DanielKehoe** [comment] 2012-06-16 08:36
I'm glad you were able to resolve the problem. I'll close the issue.

**Closed as completed by DanielKehoe** 2012-06-16 08:36 UTC

**Comment by itsEconomics** [comment] 2012-12-13 04:51
Whether I have my MailChimp API key in or leave the generated 'MAILCHIMP_API_KEY' in /models/user.rb I get this same error message when attempting to request an invite with the opt_in checked.

Started POST "/users" for 127.0.0.1 at 2012-12-12 23:48:08 -0500
Processing by RegistrationsController#create as _/_
  Parameters: {"user"=>{"email"=>"test@testy.com", "opt_in"=>"true"}}
   (0.1ms)  begin transaction
  User Exists (0.4ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = 'test@testy.com' LIMIT 1
  SQL (2.6ms)  INSERT INTO "users" ("confirmation_sent_at", "confirmation_token", "confirmed_at", "created_at", "current_sign_in_at", "current_sign_in_ip", "email", "encrypted_password", "last_sign_in_at", "last_sign_in_ip", "name", "opt_in", "remember_created_at", "reset_password_sent_at", "reset_password_token", "sign_in_count", "unconfirmed_email", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)  [["confirmation_sent_at", nil], ["confirmation_token", nil], ["confirmed_at", nil], ["created_at", Thu, 13 Dec 2012 04:48:08 UTC +00:00], ["current_sign_in_at", nil], ["current_sign_in_ip", nil], ["email", "test@testy.com"], ["encrypted_password", ""], ["last_sign_in_at", nil], ["last_sign_in_ip", nil], ["name", nil], ["opt_in", true], ["remember_created_at", nil], ["reset_password_sent_at", nil], ["reset_password_token", nil], ["sign_in_count", 0], ["unconfirmed_email", nil], ["updated_at", Thu, 13 Dec 2012 04:48:08 UTC +00:00]](0.2ms)  rollback transaction
Completed 500 Internal Server Error in 44ms

NoMethodError (undefined method `include?' for nil:NilClass):
  app/models/user.rb:57:in`new'
  app/models/user.rb:57:in `add_user_to_mailchimp'
  app/controllers/registrations_controller.rb:6:in`create'

**Comment by itsEconomics** [comment] 2013-01-27 20:49
I commented out the last line and everything works fine.

def add_user_to_mailchimp
    # if the user chooses to receive announcements, then subscribe to Mailchimp list
    unless self.email.include?('@example.com') or !self.opt_in?
      h = Hominid::API.new("8744a9ddd14d17632f7b4aacdfba6931-us6")
             list_id = h.find_list_id_by_name('visitors')
             info = { }
             h.list_subscribe(list_id, self.email, info, 'html', false, true, false, true)
             #Rails.logger.info("MAILCHIMP SUBSCRIBE: result #{result.inspect} for #{self.email}")
    end
  end
